config/routes.rb
Bandslist::Application.routes.draw do
  resources :bandnames

end

app/models/bandname.rb
class Bandname < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bandnames_controller.rb
class BandnamesController < ApplicationController
  before_action :set_bandname, only: [:show, :edit, :update, :destroy]

  # GET /bandnames
  # GET /bandnames.json
  def index
    @bandnames = Bandname.all
  end

  # GET /bandnames/1
  # GET /bandnames/1.json
  def show
  end

  # GET /bandnames/new
  def new
    @bandname = Bandname.new
  end

  # GET /bandnames/1/edit
  def edit
  end

  # POST /bandnames
  # POST /bandnames.json
  def create
    @bandname = Bandname.new(bandname_params)

    respond_to do |format|
      if @bandname.save
        format.html { redirect_to @bandname, notice: 'Bandname was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bandname }
      else
        format.html { render action: 'new' }
        format.json { render json: @bandname.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bandnames/1
  # PATCH/PUT /bandnames/1.json
  def update
    respond_to do |format|
      if @bandname.update(bandname_params)
        format.html { redirect_to @bandname, notice: 'Bandname was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bandname.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bandnames/1
  # DELETE /bandnames/1.json
  def destroy
    @bandname.destroy
    respond_to do |format|
      format.html { redirect_to bandnames_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bandname
      @bandname = Bandname.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bandname_params
      params.require(:bandname).permit(:bandname, :albumname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bandnames_helper.rb
module BandnamesHelper
end

app/views/bandnames/_form.html.erb
<%= form_for(@bandname) do |f| %>
  <% if @bandname.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bandname.errors.count, "error") %> prohibited this bandname from being saved:</h2>

      <ul>
      <% @bandname.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bandname %><br>
    <%= f.text_field :bandname %>
  </div>
  <div class="field">
    <%= f.label :albumname %><br>
    <%= f.text_field :albumname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bandnames/edit.html.erb
<h1>Editing bandname</h1>

<%= render 'form' %>

<%= link_to 'Show', @bandname %> |
<%= link_to 'Back', bandnames_path %>

app/views/bandnames/index.html.erb
<h1>Listing bandnames</h1>

<table>
  <thead>
    <tr>
      <th>Bandname</th>
      <th>Albumname</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bandnames.each do |bandname| %>
      <tr>
        <td><%= bandname.bandname %></td>
        <td><%= bandname.albumname %></td>
        <td><%= link_to 'Show', bandname %></td>
        <td><%= link_to 'Edit', edit_bandname_path(bandname) %></td>
        <td><%= link_to 'Destroy', bandname, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bandname', new_bandname_path %>

app/views/bandnames/new.html.erb
<h1>New bandname</h1>

<%= render 'form' %>

<%= link_to 'Back', bandnames_path %>

app/views/bandnames/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bandname:</strong>
  <%= @bandname.bandname %>
</p>

<p>
  <strong>Albumname:</strong>
  <%= @bandname.albumname %>
</p>

<%= link_to 'Edit', edit_bandname_path(@bandname) %> |
<%= link_to 'Back', bandnames_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bandslist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>